#!/usr/bin/env sh
set -eu

ENV_FILE="${1:?Usage: $0 <env-file>}"

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${SESSION_SECRET:?SESSION_SECRET is required}"
: "${R2_PUBLIC_BASE_URL:?R2_PUBLIC_BASE_URL is required}"

umask 077
cat > "$ENV_FILE" <<EOF
NODE_ENV=production
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
SESSION_SECRET=$SESSION_SECRET
R2_PUBLIC_BASE_URL=$R2_PUBLIC_BASE_URL
NEXT_PUBLIC_NEW_RELIC_ACCOUNT_ID=${NEXT_PUBLIC_NEW_RELIC_ACCOUNT_ID:-}
NEXT_PUBLIC_NEW_RELIC_AGENT_ID=${NEXT_PUBLIC_NEW_RELIC_AGENT_ID:-}
NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID=${NEXT_PUBLIC_NEW_RELIC_APPLICATION_ID:-}
NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY=${NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY:-}
NEXT_PUBLIC_NEW_RELIC_TRUST_KEY=${NEXT_PUBLIC_NEW_RELIC_TRUST_KEY:-}
APP_PORT=${APP_PORT:-3000}
NGINX_PORT=${NGINX_PORT:-8080}
SERVER_NAME=${SERVER_NAME:-_}
TLS_CERT_NAME=${TLS_CERT_NAME:-app}
EOF

chmod 600 "$ENV_FILE"
